---
# pg-backup Ansible Role - Metadata

galaxy_info:
  author: Jens-Christian Fischer
  description: Deploy pg-backup PostgreSQL backup tool with systemd timer
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble

  galaxy_tags:
    - postgresql
    - backup
    - database
    - systemd

dependencies: []
